site_name: My Docs
theme:
  name: material
  features:
    - content.action.edit
   # - content.action.view
repo_url: https://github.com/jondelara/mkdocssite2
repo_name: jondelara/mkdocssite2
edit_uri: edit/main/gitsite/docs